# Generated by Django 5.2.7 on 2025-12-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_education'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skill',
            name='icon',
            field=models.CharField(blank=True, help_text="e.g. 'devicon-python-plain' from devicon.dev", max_length=50),
        ),
    ]
